'use client';
import { getAnalytics } from "firebase/analytics";
import { getApp, getApps, initializeApp, type FirebaseApp } from 'firebase/app';
import { getAuth, type Auth } from 'firebase/auth';
import { getFirestore, type Firestore } from 'firebase/firestore';

// Note: This file will be overwritten by the Firebase integration service.
// Do not edit this file manually.
const firebaseConfig = {
  apiKey: "AIzaSyBOgag8oO-USYoMBVzlhJMrbepn493c_-c",
  authDomain: "gen-lang-client-0845556068.firebaseapp.com",
  projectId: "gen-lang-client-0845556068",
  storageBucket: "gen-lang-client-0845556068.firebasestorage.app",
  messagingSenderId: "255950860091",
  appId: "1:255950860091:web:5aebe195c04b06ee5fd11e",
  measurementId: "G-B5C75MBTCJ"
};

function createFirebaseApp(config: any): FirebaseApp {
  if (getApps().length > 0) {
    return getApp();
  }
  return initializeApp(config);
}


export async function initializeFirebase(): Promise<{
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
}> {
  const app = createFirebaseApp(firebaseConfig);
  const auth = getAuth(app);
  const firestore = getFirestore(app);

  if (typeof window !== "undefined") {
    if ("measurementId" in firebaseConfig) {
      getAnalytics(app);
    }
  }

  return { app, auth, firestore };
}

export {
  useCollection,
  useDoc,
} from '@/firebase/firestore/hooks';
export { useUser } from '@/firebase/auth/use-user';
export {
  FirebaseProvider,
  useFirebase,
  useFirebaseApp,
  useFirestore,
  useAuth,
} from '@/firebase/provider';
export { FirebaseClientProvider } from '@/firebase/client-provider';