
'use client';
import { getAnalytics } from "firebase/analytics";
import { getApp, getApps, initializeApp, type FirebaseApp } from 'firebase/app';
import { getAuth, type Auth } from 'firebase/auth';
import { getFirestore, type Firestore } from 'firebase/firestore';

// Note: This file will be overwritten by the Firebase integration service.
// Do not edit this file manually.
const firebaseConfig = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "gen-lang-client-0845556068",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID",
  measurementId: "YOUR_MEASUREMENT_ID"
};


function createFirebaseApp(config: any): FirebaseApp {
  if (getApps().length > 0) {
    return getApp();
  }

  const app = initializeApp(config);

  if (typeof window !== "undefined") {
    if ("measurementId" in config) {
      getAnalytics(app);
    }
  }

  return app;
}


export async function initializeFirebase(): Promise<{
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
}> {
  const app = createFirebaseApp(firebaseConfig);
  const auth = getAuth(app);
  const firestore = getFirestore(app);

  return { app, auth, firestore };
}

export {
  useCollection,
  useDoc,
} from '@/firebase/firestore/hooks';
export { useUser } from '@/firebase/auth/use-user';
export {
  FirebaseProvider,
  useFirebase,
  useFirebaseApp,
  useFirestore,
  useAuth,
} from '@/firebase/provider';
export { FirebaseClientProvider } from '@/firebase/client-provider';
